### ISSUE TITLE
Segment Fault (core dumped)

### ISSUE THREAD

**Issue by notaduck** [rliou92/umonitor#1]
It is probably me doing something wrong here.  
I installed umonitor from AUR and used arandr to generate a config. Then I tried to save the config with umonitor
```
[danile@danile-pc ~]$ umonitor --save .screenlayout/home.sh 
Segmentation fault (core dumped)
```

**Comment by rliou92** [comment]
When I say "use arandr to generate a config", I mean use arandr to setup the position and resolution of your monitors, not generating an arandr configuration file. umonitor doesn't use arandr's configuration file. umonitor uses its own configuration file located in `~/.config/umon2.conf`. Maybe I should only use configuration when referring to configuration files, and setup when referring to the monitor resolution and position settings. When your monitor position and resolution are correctly setup, you should run `umonitor --save <profile_name>` to save the setup into umonitor's configuration file, where profile_name is an easy to remember name of your current setup. That way, you can easily load your setup by typing `umonitor --load <profile_name>` in the future. 

I think I confused you by using "configuration" when I meant the setup of the resolution and positions of your monitors, not the configuration file generated by arandr. I have been loose with my wording in the Readme, which has lead to this confusion. I will rewrite the Readme to be more precise.

**Comment by notaduck** [comment]
Aaaha I see! Thanks for the thorough explanation!  
But yes I think you are abselutley right regarding " I think I confused you by using "configuration"
