### ISSUE TITLE
Umonitor doesn't apply rotation

### ISSUE THREAD

**Issue by notaduck** [rliou92/umonitor#2]
I don't know if this is a feature which is not implemented but every time I load my profile I have to use xrandr to roate my screen in order to get in in portrait mode.

**Comment by rliou92** [comment]
Yea, this feature has not been implemented, mainly because I don't use rotation. I can work on it in a month or so.

**Comment by notaduck** [comment]
It would be great if it is something you could implement! I use this everyday and multiple times :D 
This is a great peace of software you have written!

**Comment by rliou92** [comment]
Thanks for the kind words :) I am certainly much more motivated to work on this now!

**Comment by rliou92** [comment]
Hi @notaduck 

I've updated the code. In order to start saving resolution, first please delete the profile, then use the newly updated program to save the profile. Afterwards, rotation should work :) 

Let me know if anything goes wrong.

**Comment by notaduck** [comment]
I will try it tommorw when I come home and report back ;) thank you so much for doing this!

**Comment by notaduck** [comment]
I'm going to repoen this "issue" for some odd reason it doesn't rotate anymore?
I deleted the old profile, made everything look like I wanted it to be wit arandr and saved it with Umonitor.
But it doesn't seem to work.(The roation part)

**Comment by rliou92** [comment]
Hmmm seems to be working fine for me when I test it.

Can you post:
1. `umon.conf`
1. `umonitor --load <your_profile> --verbose`

**Comment by notaduck** [comment]
Sry for the late reply! I have been quite busy this week.
```
cat umon.conf
home : 
{
  Screen : 
  {
    width = 4000;
    height = 2560;
    widthMM = 1054;
    heightMM = 675;
  };
  Monitors : 
  {
    eDP1 : 
    {
      EDID = "SHP unknown";
      resolution : 
      {
        x = 0;
        y = 0;
      };
      pos : 
      {
        x = 0;
        y = 0;
      };
    };
    DP2-1 : 
    {
      EDID = "DEL DELL U2715H";
      resolution : 
      {
        x = 2560;
        y = 1440;
      };
      pos : 
      {
        x = 0;
        y = 512;
      };
    };
    HDMI1 : 
    {
      EDID = "DEL DELL U2515H";
      resolution : 
      {
        x = 2560;
        y = 1440;
      };
      pos : 
      {
        x = 2560;
        y = 0;
      };
    };
  };
};
```

```
 umonitor --l home --verbose
Segmentation fault (core dumped)
```

**Comment by rliou92** [comment]
From the configuration file, there is no rotation information. Did you make sure you ran ``umonitor --save home`` using the most up-to-date version of umonitor?

**Comment by notaduck** [comment]
Sry! I actually forgot to reply, but it still work flawless! I'mm still using it everyday
