### ISSUE TITLE
An error on "make"

### ISSUE THREAD

**Issue by mikehlim** [rliou92/umonitor#7]
Any dependency packages? I'm running it on Ubuntu 18.04
===================================================
mlim@linux:~/umonitor-master$ make
gcc -Wall -c src/screen.c -o obj/screen.o
In file included from src/screen.c:1:0:
src/common.h:5:10: fatal error: libconfig.h: No such file or directory
 #include <libconfig.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:33: recipe for target 'obj/screen.o' failed
make: *** [obj/screen.o] Error 1

**Comment by rliou92** [comment]
Yes, libconfig is the missing package.

**Comment by mikehlim** [comment]
Thank you. Successfully done. 
make 
sudo make install

another error is "Configuration file not found" 
mlim@linux:~$ umonitor --listen --quiet&
[2] 5754
mlim@linux:~$ Configuration file not found.

**Comment by mikehlim** [comment]
Nevermind, I should run the "umonitor --save home"  Thank you.
